# NUMPY NOTES
## MADE BY :-<U>TUSHAR SETHIYA</U>
## GUIDED BY :- <U>ELLIE (CODE OF FUTURE)</U>

## CONTENT
* [INTRODUCTION](#1)
* [CREATING ARRAY AND DIMENSIONAL ARRAY](#2)
* [INDEXING ARRAY](#3)
* [SLICING ARRAY](#4)
* [VIEW AND COPY](#5)
* [SHAPING AND RESHAPING ARRAY](#6)
* [BASIC OPRATION ON ARRAY](#7)
* [ITERATING IN ARRYS](#8)
* [JOINING ARRAY](#9)
* [SEARCHING IN ARRAY](#10)
* [SORTING AND FILTERING](#11)
* [RANDOM](#12)

## NUMPY INTRODUCTION <a class="anchor" id="1"></a>
<B>NUMPY</B> IS A PYTHON LIBRARY USED FOR WORKING WITH ARRAYS.

IT WAS CREATED BY <B> TRAVIS OLIPHANT </B> IN <B>2005</B> IT IS AN OPEN SOURCE PROJECT AND WE CAN USE IT FREELY.

NUMPY STANDS FOR <B>NUMERICAL PYTHON</B>

NUMPY PROVIDES TRADITONAL ARRAY OBJECTS THAT ARE 50X FASTER THAN PYTHON LIST

NUMPY IS A PYTHON LIBRARY AND IS WRITTEN PARTIALLY IN PYTHON BUT MOST OF THE PARTS THAT REQUIRE FASTER COMPUTATION ARE WRITTEN IN C AND C++

## WHY IS NUMPY FASTER THAN LISTS?
NUMPY ARRAY ARE STORED AT ONE CONTINUOS PLACE IN MEMORY UNLIKE LISTS SO PROCESSES CAN ACCESS THEN AND MANIPULATE THEM VERY EFFICIENTLY.THIS BEHAVIOUR IS CALLED LOCALITY OF REFRENCE IN COMPUTER SCIENCE.

In [1]:
#NUMPY PACKAGE CAN BE INSTALLED USING 
!pip install numpy

In [2]:
#now we can import numpy library 
import numpy as np     #generally numpy is stored under alias np

In [3]:
#we can also check the version of numpy 
print(np.__version__)

1.21.5


## CREATING ARRAY AND DIMENSIONAL ARRAY<a class="anchor" id="2"></a>

In [4]:
#The array object in numpy is called ndarray
#To create an ndarray we can pass a list or tuple into array method can it will be converted into nd array

arr = np.array((1,2,3,4,5)) #or arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
#DIMENSION IN ARRAY IS ONE LEVEL OFA ARRAY DEPTH

#### 0-D ARRAYS
0-D ARRAY OR SCALERS ARE ELEMENT IN ARRAY.EACH VALUE IN ARRAY IS 0-D ARRAY

In [7]:
ZERO_D_ARRAY = np.array(45)
#lets print the array
print(ZERO_D_ARRAY)

#lets check the type of object
print(type(ZERO_D_ARRAY))

#lets check the dimenssion of the array ndim method can be used to check the dimmension of the array
print(ZERO_D_ARRAY.ndim)

45
<class 'numpy.ndarray'>
0


#### 1-D ARRAYS
AN ARRAY THAT HAS 0-D ARRAYS AS ITS ELEMENTS IS CALLED UNI-DIMENSIONAL ARRAY
THESE ARE THE MOST COMMON AND BASICS ARRAYS

In [8]:
ONE_D_ARRAY = np.array((1,2,3,4,5,6,7,8,9))

print(ONE_D_ARRAY)

print(type(ONE_D_ARRAY))

print(ONE_D_ARRAY.ndim)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1


#### 2-D ARRAYS
AN ARRAY THAT HAS 1-D ARRAYS AS ITS ELEMENTS IS CALLED 2-D ARRAY THESE ARE OFTEN USED TO REPRESENT MATRIX

In [9]:
TWO_D_ARRAY = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(TWO_D_ARRAY)

print(type(TWO_D_ARRAY))

print(TWO_D_ARRAY.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2


In [10]:
#we can also use ndmin argument to create a array of required dimennsion
FIVE_D_ARRAY = np.array([1,2,3,4,5],ndmin=5)

print(FIVE_D_ARRAY)

print(type(FIVE_D_ARRAY))

print(FIVE_D_ARRAY.ndim)

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>
5


## INDEXING ARRAY<a class="anchor" id="3"></a>
ARRAY INDEXING IS SAME AS ACCESSING AN ARRAY ELEMENT
YOU CAN ACCESS AN ARRAY ELEMENT BY REFREING TO ITS INDEX NUMBER
THE INDEXES IN ARRAY START WITH 0 MEANING THE FIRST ELEMENT HAS INDEX 0 AND THE SECOND HAS INDEX 1

In [11]:
#LETS GET THE ELEMENTS FROM THE 1-D ARRAY
ONE_D_ARRAY

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#FIRST ELEMENT FROM 1-D ARRAY
ONE_D_ARRAY[0]

1

In [13]:
#FOURTH ELEMENT OF 1-D ARRAY
ONE_D_ARRAY[3]

4

In [14]:
#LETS GET THE ELEMENT OF 2-D ARRAY
#TO ACCESS ELEMENTS FROM 2-D ARRAY WE CAN USE COMMA SEPRATED INTEGER RECPRWESENTING THE DIMENSION AND THE INDEX OF THE ELEMENT
TWO_D_ARRAY

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#THIRD ELEMENT FROM SECOND ROW
TWO_D_ARRAY[1,2]

#HERE THE FIRST NUMBER (1) CORRESPOND TO THE FIRST DIMNESION AND IN FIRST DIMENSION WE HAVE [1 2 3 ][4 5 6][7 8 9]
#NOW WE HAVE INPUTED 1 SO ITS CORRESPOND TO THE SECOND ELEMENT IN THE ARRAY SO NOW WE ARE LEFT WITH
#[4 5 6]

#THE SECOND NUMBER (2) TELLS THE INDEX AS WE ARE ONLY LEFT WITH WITH [4 5 6] AND WE HAVE GIVEN 2 SO IT WILL GIVE THE
#3 ELEMENT IN THE ARRAY WHICH IS 6

6

In [16]:
print(FIVE_D_ARRAY)

[[[[[1 2 3 4 5]]]]]


In [17]:
FIVE_D_ARRAY[0,0,0,0,4]

5

In [18]:
#we can also use negative indexing
ONE_D_ARRAY

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ONE_D_ARRAY[-1] #IT WILL GIVE US THE LAST NUMBER FROM THE ARRAY

9

## SLICING ARRAY<a class="anchor" id="4"></a>
Slicing in python means taking element from one given index to other given index.

In this case we pass slice instead of index like this <b>[start:end]</b>

We can also define steps <b>[start:end:step]</b>

If we dont pass start it will consider 0

If we dont pass end it will conider len of array

If we dont pass step it will consider 1


In [20]:
#SLICE ELEMENT FROM 3 TO 8 FROM ONE_D_ARRAY
ONE_D_ARRAY

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ONE_D_ARRAY[2:8]    #START WILL BE INCLUDED BUT END INDE WILL NOT BE INCLUED

array([3, 4, 5, 6, 7, 8])

In [22]:
#SLICE ELEMENT UPTO 5 FROM THE START 
ONE_D_ARRAY[:5]      #START IS NOT PROVIDED BY DEFAULT IT IS 0

array([1, 2, 3, 4, 5])

In [23]:
#ALICE ELEMENT FROM 5 UPTO LAST
ONE_D_ARRAY[4:]

array([5, 6, 7, 8, 9])

In [24]:
#SLICE ALTERNATE ELEMENT BETWEEN 2 AND 8
ONE_D_ARRAY[1:8:2]

array([2, 4, 6, 8])

In [25]:
#NEGTIVE SLICING 
#SLICEOUT LAST FOUR ELEMENT FROM ONE_S_ARRAY
ONE_D_ARRAY[-4:]

array([6, 7, 8, 9])

In [26]:
#NOW LETS TRY TO ALICE A TWO_D_ARRAY
TWO_D_ARRAY

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
#SLICE OUT 5 6 8 9 FROM THE ARRAY
TWO_D_ARRAY[1:,1:]

array([[5, 6],
       [8, 9]])

In [28]:
#SLICE OUT 2,8 FROM TWO_D_ARRAY
TWO_D_ARRAY[[0,2],1]

array([2, 8])

## VIEW AND COPY<a class="anchor" id="5" ></a>
COPY IS NEW ARRAY WHILE VIEW IS ORIGINAL ARRAY

COPY OWNS THE DATA ANY CHANGE MADE IN THE COPY WILL NOT AFFECT THE ORIGINAL ARRAY AND ANY CHANGE AMDE TO ORIGINAL ARRAY WILLNOT AFFECT THE COPY

VIEW DOES NOT OWN THE DATA ANY CHANGE MADE TO THE VIEW WILL AFFECT THE ORIGINAL DATA

In [29]:
ORIGINAL_ARRAY=np.array([1,2,3,4,5,6])
COPY_ARRAY=ORIGINAL_ARRAY.copy()      #CREATE COPY OF ORIGINAL_ARRAY
VIEW_ARRAY=ORIGINAL_ARRAY.view()      #CREATE VIEW OF ORIGINAL ARRAY

In [30]:
print(COPY_ARRAY)

[1 2 3 4 5 6]


In [31]:
print(VIEW_ARRAY)

[1 2 3 4 5 6]


In [32]:
ORIGINAL_ARRAY[-1]=30

In [33]:
ORIGINAL_ARRAY

array([ 1,  2,  3,  4,  5, 30])

In [34]:
COPY_ARRAY    #COPY ARRAY IS NOT AFFECTED BY CHANGE MADE INTO THE ORIGINAL ARRAY

array([1, 2, 3, 4, 5, 6])

In [35]:
VIEW_ARRAY    #VIEW ARRAY IS AFFECTED BY THE CHANGE IN ORIGINAL ARRAY

array([ 1,  2,  3,  4,  5, 30])

In [36]:
COPY_ARRAY.base    #as the COPY_ARRAY OWNS THE DATA IT WILL RETURN NONE

In [37]:
VIEW_ARRAY.base    #VIEW_ARRAY WILL RETURN THE ORIGINAL ARRAY 

array([ 1,  2,  3,  4,  5, 30])

## SHAPING AND RESHAPING ARRAY <a class="anchor" id="6"></a>

THE SHAPE OF ARRAY IS THE NUMBER OF ELEMENTS IN EACH DIMENSION

NUMPY HAVE AN ATTRIBUTE CALLED SHAPE THAT RETURNS A TUPLE WITH EACH INDEX HAVING THE NUMBER OF CORRESPONDING ELEMENT

In [38]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [39]:
arr.shape  #length of tuple tells the dimension of the array

(2, 4)

In [40]:
arr1=np.array(1,ndmin=5)
arr1

array([[[[[1]]]]])

In [41]:
arr1.shape

(1, 1, 1, 1, 1)

In [42]:
#what we have array of different length
arr2=np.array([[1,2,3,4,5],[6,7,8,9]])
arr2.shape
#so it will give us a little warning sign and display the tuple which contain number of element in outer dimmnesion

/var/folders/k3/5sc5mpfj02sg1rb5ytlt13yh0000gn/T/ipykernel_11194/485911301.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2=np.array([[1,2,3,4,5],[6,7,8,9]])


(2,)

In [43]:
#lets suppose we have an array of students ages and we have 3 students of each age
student = np.array([19,19,19,20,20,20,21,21,21])
#we also have there average exam score
exam_score=np.array([57,60,65,65,72,7559,63,70,])

In [44]:
#now lets reshape the exam score
exam_split=exam_score.reshape(3,3)
exam_split

ValueError: cannot reshape array of size 8 into shape (3,3)

In [45]:
exam_score.size

8

In [46]:
#we cannot reshape each array
exam_split1=exam_score.reshape(2,4)
#for reshaping size of each element should be same

In [47]:
exam_score.size

8

In [48]:
#we can also reahpe in any dimension untill the size of both the array is same
exam_split1=exam_score.reshape(3,3,1)
exam_split1

ValueError: cannot reshape array of size 8 into shape (3,3,1)

In [49]:
arr_shape=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr_shape)
#if we want to reshape into a dimnsion in which one dimnession is unknown then we can replace it with -1 
#and python will automaticlly calculate the unknown dimension

arr_reshape=arr_shape.reshape(2,2,-1)
print(arr_reshape)
print(arr_reshape.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [50]:
print(arr_reshape)

arr_reshape_1=arr_reshape.reshape(-1)    #when we insert -1 in the argument then it will flatten the array
print(arr_reshape_1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## BASIC OPERATION ON ARRAY <a class="anchor" id=7></a>

In [51]:
#we can create an array between numbers like we can do with list and the arange command
a=np.arange(0,5)    #it will produce a one dimension array with number in the given range          

In [52]:
#lets create another sample array
b= np.array([4,6,19,23,45])

In [53]:
print(a)
print(b)

[0 1 2 3 4]
[ 4  6 19 23 45]


In [54]:
#basic mathematical operation
#there is a elementwise operation


#addition
print(a+b)

#substraction
print(a-b)

#multiplication
print(a*b)

#divison
print(a/b)

#exponential
print(b**a)



[ 4  7 21 26 49]
[ -4  -5 -17 -20 -41]
[  0   6  38  69 180]
[0.         0.16666667 0.10526316 0.13043478 0.08888889]
[      1       6     361   12167 4100625]


In [55]:
#squaring all element in the array
print(a**2)

#square root all the element
print(np.sqrt(a))      #sqrt is a method in numpy

#multiplying array by ac onstant value
print(a*3)

#check for boolean value in the list
print(a<3)    #it will give as a boolean value checking each value if it is greater or smaller than the given value

[ 0  1  4  9 16]
[0.         1.         1.41421356 1.73205081 2.        ]
[ 0  3  6  9 12]
[ True  True  True False False]


In [56]:
# operation that come in handy for data analysis
one_dim=np.array([1,2,3,4,5])
two_dim=np.array([[1,2,3],[4,5,6]])

#summations
#summing up all the eleemnt in a one_d_array
print(" our array =",one_dim,"\n","sum of array=",sum(one_dim))
print("\n")
#summation of twto_dim_array
print("our two d array=","\n",two_dim)
print(sum(two_dim))   #it will give us the sum along the particular axis in this case along the column

#what if we want sum of all the elements in multi_dim array
print(two_dim.sum())

#maximum and minmum in the array'
print(one_dim.max())  
print(max(one_dim))    #above both the statement are right

print(two_dim.max())   #similarly we cn also calculate the min_value

#lets consider a 2_d array
two_d_array=np.array([[1,2,3],[4,5,6],[7,8,9]])

#if we want sum across columns
print(two_d_array.sum(axis=0))

#if we want sum across rows
print(two_d_array.sum(axis=1))

#if we want sum of all the elements
print(two_d_array.sum())

#similarly we can also find min and max


 our array = [1 2 3 4 5] 
 sum of array= 15


our two d array= 
 [[1 2 3]
 [4 5 6]]
[5 7 9]
21
5
5
6
[12 15 18]
[ 6 15 24]
45


## ITERATING IN ARRAYS<a class="anchor" id="8"></a>
ITEREATING MEANS GOING THROUGH ELEMENT ONE BY ONE

AS WE DEAL WITH MULTI_DIMENSIOBNAL ARRAY IN NUMPY WE CAN DO THIS USING BASIC FOR LOOP OF PYTHON

In [57]:
#creating a one_d_array
one_dim=np.arange(1,6)
print(one_dim)

#iterating over one_d_array
for element in one_dim:
    print(element)
    
#craeting a two_d_array
two_dim=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dim)

#iterating over two_d_array
# as it is a 2_d array and there are 3 element in the outer dim
for i in two_dim:
    print(i)
    
#what if we want to iterate over all the values
#method 1-using a nested for loop
for i in two_dim:
    for j in i:
        print(j)
        
#method 2-by reshaping the array
for i in two_dim.reshape(-1):
    print(i)

#method 3-my usng numpy method "nditer"

for i in np.nditer(two_dim):
    print(i)
    
#figuring out index using "ndenumerate"

for index,element in np.ndenumerate(two_dim):
    print(index,element)

[1 2 3 4 5]
1
2
3
4
5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


## JOINING AND SPLITTING<a class=anchor id=9></a>

JOINING MEANS PUTTING CONTENT OF TWO OR MORE ARRAYS IN A SINGLE ARRAY

IN SQL WE JOIN ARRAYS ON THE BASIS OF KEY,WHILE IN NUMPY WE JOIN SRRAYS ON THE BASIS OF AXIS

WE PASS A SEQUENCE OF AARAYS THAT WE WANT TO JOIN TO THE CONCATENATE FUNCTION ALONG WITH THE AXIS.BY DEFAULT AXIS IS 0

In [72]:
first_array=np.arange(1,6)
print(first_array)

print("\n")

second_array=np.arange(6,11)
print(second_array)

print("\n")
#for a single dimenssion array there is only one axis
join_array_0_axis=np.concatenate((first_array,second_array))
print(join_array_0_axis)


[1 2 3 4 5]


[ 6  7  8  9 10]


[ 1  2  3  4  5  6  7  8  9 10]


In [84]:
two_d_array_first=np.array([[1,2],[3,4]])
print("first_array=\n",two_d_array_first)

two_d_array_second=np.array([[5,6],[7,8]])
print("second_array=\n",two_d_array_second)


#as axis is not mentioned array will be concatenated along column or zero_axis
concatenated_array_0_axis=np.concatenate((two_d_array_first,two_d_array_second))
print("concatenated array=\n",concatenated_array_0_axis)

#concatenating along rows
concatenated_array_1_axis=np.concatenate((two_d_array_first,two_d_array_second),axis=1)
print("concatenated array=\n",concatenated_array_1_axis)

first_array=
 [[1 2]
 [3 4]]
second_array=
 [[5 6]
 [7 8]]
concatenated array=
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenated array=
 [[1 2 5 6]
 [3 4 7 8]]


#### stacking

stacking is same as concatenation the only difference is stacking is done along a new axis

with stacking we can concatenate two 1_d array along the second axis

In [95]:
first_array=np.array([1,2,3,4,5])
second_array=np.array([6,7,8,9,10])

stack_0_axis=np.stack((first_array,second_array),axis=0)
print(stack_0_axis)

stack_1_axis=np.stack((first_array,second_array),axis=1)
print(stack_1_axis)

#we can also use some helpfull function
stack_horizontal=np.hstack((first_array,second_array))
print(stack_horizontal)

stack_verticle=np.vstack((first_array,second_array))
print(stack_verticle)

stack_depth=np.dstack((first_array,second_array))
print(stack_depth)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


## SPLITING ARRAY

SPLITING IS REVERSE OPERATION OF JOINING

JOINIG MERGES MULTIPLE ARRAYS INTO ONE AND SPLITTING BREAKS ONE ARRAY INTO MULTIPLE

WE USE ARRAY_SPLIT() FOR SPLITTING ARRAYS WE PASS IN THE ARRAY WE WANT TO SPLIT AND THE NUMBER OF SPLITS

In [99]:
array1=np.array((1,2,3,4,5,6,7,8,9))
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
#now lets aplit above array
new_array=np.array_split(array1,3)
print(new_array[0])
print(new_array[1])
print(new_array[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [113]:
#if array will have less element than it will adjust from end accordingly
new_array_2=np.array_split(array1,4)
print(new_array_2)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [116]:
#similarly a 2_d array can be split
array2=np.array([[1,2],[3,4],[5,6],[7,8]])
print(array2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [120]:
new_array_3=np.array_split(array2,4)
new_array_3

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

In [125]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])

#we can split the above array along both the axis
#a 2-d array when splitted will result only in a 2_d array
new_array_columns=np.array_split(array3,3)
print(new_array_columns)

new_array_rows=np.array_split(array3,3,axis=1)
print(new_array_rows)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [128]:
array4=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_array_horizontal=np.hsplit(array4,3)
print(new_array_horizontal)

new_array_verticle=np.vsplit(array4,3)
print(new_array_verticle)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [136]:
#split and array_split both works same but split will give an error when splitting size is inappropriate

array=np.arange(1,13)
print(array)

first_split=np.split(array,4)
print(first_split)

first_array_split=np.array_split(array,4)
print(first_array_split)

second_array_split=np.array_split(array,5)
print(second_array_split)

second_array=np.split(array,5)     #this will give an error 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]


ValueError: array split does not result in an equal division

## SEARCHING IN ARRAYS <a class=anchor id=10></a>
WE CAN SEARCH IN ARRAY FOR A CERTAIN VALUE AND CAN RETURN INDEX OF THAT VALUE

In [138]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
x=np.where(array==4)
print(x)

(array([3]),)


In [143]:
#suppose we are searching for an element which is repeated multiple time in the array
#it will provide us a tulple of index where value = element
array=np.array((1,2,3,3,3,3,4,5,63,3,3))
x=np.where(array==3)
print(x)

(array([ 2,  3,  4,  5,  9, 10]),)


In [146]:
#we can also find the index of the even value
#it will provide us index of all the even numbers
array = np.arange(1,11)
x=np.where(array%2==0)
print(x)

(array([1, 3, 5, 7, 9]),)


In [148]:
#if we want index of element less than 5
array=np.arange(1,11)
x=np.where(array<5)
print(x)

(array([0, 1, 2, 3]),)


In [152]:
#lets see if number is divivsible by 3
array = np.arange(1,11)
divisible_by_3=np.where(array%3==0)
print(array)    #it will give the index of element divisible by 3

print(array[divisible_by_3])    #it will give the number

[ 1  2  3  4  5  6  7  8  9 10]
[3 6 9]


## SORTING AND FILTERING <a order=anchor id=11></a>
SORTING MEANS PUTTING ELEMENTS IN AN ORDERED SEQUENCE ASCENDING OR DESCENDING ORDER

THE NUMPY NDARRAY HAS A FUNCTION CALLED SORT()

In [154]:
fruits=np.array(["graphes","apple","banana","mango"])
print(fruits)

['graphes' 'apple' 'banana' 'mango']


In [158]:
print(np.sort(fruits))

['apple' 'banana' 'graphes' 'mango']


In [159]:
#sorting a 2-D array
array=np.array([[4,3,5],[6,2,7]])
print(np.sort(array))

[[3 4 5]
 [2 6 7]]


#### FILTERING
GETTING SOME ELEMENT OUT OF AN EXISTING ARRAY AND CREATING A NEW ARRAY OUT OF THEM OS CALLED FILTERING

IN NUMPY FILTERING IS DONE USING A BOOLEAN LIST

In [160]:
array=np.array([1,2,3,4,5,6,7,8])
filt=[True,False,True,False,True,False,True,True]

array[filt]

array([1, 3, 5, 7, 8])

In [163]:
#we can also filter as per our condition
greater_than_five=array[array>5]
print(greater_than_five)

[6 7 8]


In [172]:
array=np.array([1,2,3,5,6,7])
#this value will return the index where the inputted value should be inserted
#to maintain the order
x=np.searchsorted(array,4)
print(x)

3


## RANDOM MODULE<a class=anchor id=12></a>

RANDOM NUMBER DOES NOT MEAN A DIFFERENT NUMBER EVERY TIME RANDOM MEANS SOMETHING THAT CAN NOT BE PREDICTED LOGICALLY

In [173]:
#importing random module
from numpy import random

In [208]:
#random module has different function

#randint(low,high,size=number_of_integer_required)-uniformly distributed integers in a given range
#it will include low value(by default low value is 0) from the range and exclude high value

x=np.random.randint(0,100,size=5)    #it will generate a array of 5 random value between >=0 and <100
print(x)

y=np.random.randint(0,1000,size=(2,3))
print(y)

[67 69 90  5 76]
[[277 533 374]
 [533 250 841]]


In [214]:
#rand-this function will generate a random float value between 0 and 1
#it will take the argument for the shape of the array
x=np.random.rand(5)    #it will generate 5 random float value between 0 and 1
print(x)

y=np.random.rand(5,6)   #it will return an array of 5X6
print(y)

[0.78808234 0.76140689 0.3133889  0.11813394 0.99706089]
[[0.70480652 0.08570391 0.15566553 0.33758803 0.89547197 0.02369605]
 [0.87262377 0.16518836 0.01697583 0.11046051 0.21930194 0.34996659]
 [0.1340481  0.92755009 0.92260676 0.70723781 0.72797334 0.56603411]
 [0.59977345 0.80373415 0.71760721 0.79145481 0.42687344 0.76276079]
 [0.06046305 0.52865947 0.5397946  0.23436608 0.73855899 0.57931862]]


In [224]:
#choice-this function will chose a random value from array
x=np.random.choice([1,2,3,4,5])     #this will chose a single random value from the array
print(x)

y=np.random.choice([1,2,3,4,5],size=5)   #this will generate 5 random number from the above list
print(y)

3
[4 1 4 5 2]


In [239]:
#there is a function in numpy which can generate a zeros

zero_1=np.zeros(3)   #here it will give an array containg 3 zeros
print(zero_1) 

zero_2=np.zeros(shape=(3,3))    #it will take an argumnt shape which will return an array
print(zero_2)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [243]:
#there is another function in numpy which can generate one

one_1=np.ones(3)
print(one_1)

one_2=np.ones(shape=(3,3))
print(one_2)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [246]:
#we can also generate a identity array
identity=np.identity(3)    #it will take a single value and give a square matrix
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
